### ISSUE TITLE
add libasound2-plugins:i386 to pcsx2 dependencies

### ISSUE THREAD

**Issue by Twitch0815** [RetroPie/RetroPie-Setup#1724] opened 2016-10-26 21:12 UTC
Tested a few systems, with different failing rates installing pcsx2 in the Retropie X86 installation. 

sudo apt-get install libasound2-plugins:i386
is the fix for me. 

Possibly problems with 64 bit os's and 32 bit dependenceis.

**Comment by Twitch0815** [comment] 2016-10-26 21:36
http://pastebin.com/af7Er565

**Comment by joolswills** [comment] 2016-10-26 21:36
The retropie module for PCSX just installs the debian package, so im not sure it would be missing a dependency but need more details. Also please provide a log and information of what you are running on. Note: as mentioned when opening a ticket - we prefer the forum to be used first as many issues can be down to configuration etc and otherwise this issue tracker would just be full of support questions.

**Comment by Twitch0815** [comment] 2016-10-26 21:37
This is on Ubuntu 16.04.1 X64 Bit   up to date on apt-get update and upgrade

**Comment by joolswills** [comment] 2016-10-26 21:37
That is an issue with your install / dependencies. Have you got 3rd party PPAs installed or did you upgrade from an earlier version ?

**Comment by Twitch0815** [comment] 2016-10-26 21:38
No this was base install.  Following Retropie X86 installation to a T.    
The only PPA package that was installed was the Nvidia PPA to upgrade the Nvidia driver

**Comment by Twitch0815** [comment] 2016-10-26 21:39
And the behavior was consistent with a seperate machine, Macbook pro identical installation log was the same but that did not have any third party PPA's  I will produce a log from that machine.

**Comment by joolswills** [comment] 2016-10-26 21:39
aah it's because it's a i386 only package.  I will need to look into that.

**Comment by joolswills** [comment] 2016-10-26 21:49
it requires other i386 packages also, so it's possible you just had some existing dependency issue on your system that you resolved when manually installing. I'll have to check on my system.

**Comment by joolswills** [comment] 2016-10-26 22:12
I did some testing - the problem is likely due to some different paclages on your system that break the pcsx dependencies - it installs fine on a clean 16.04 - I suspect the graphics driver ppa did it. I had this ppa enabled https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers (to fix a bug on 16.04) and it broke pcsx2 installing due to mismatch of package versions and the pcsx package dependencies . I removed it and pcsx2 installs normally.

Not something that can be fixed in RetroPie-Setup

**Closed by joolswills** 2016-10-26 22:12 UTC
