### ISSUE TITLE
Xbox One controllers still not working

### ISSUE THREAD

**Issue by trixster1979** [RetroPie/RetroPie-Setup#1277] opened 2016-02-20 14:58 UTC
Despite the recent update to xboxdrv to try and resolve this issue, Xbox one controllers still do not seem to be working.

I've updated the setup script, built xboxdrv from source but no luck. I've also tried installing the binary but that still doesn't help.

Attaching thr controller brings up a load of dialogue in the console, and jstest seems to recognise it too, but pressing the buttons does not toggle a response from jstest.

Emulationstation will not recognise that the pad is connected either.

**Comment by zerojay** [comment] 2016-02-20 15:55
Can you please post the output of sudo lsusb for us here?

**Comment by trixster1979** [comment] 2016-02-20 17:28
Bus 001 Device 005: ID 046d:c52e Logitech, Inc.
Bus 001 Device 007: ID 045e:02d1 Microsoft Corp.
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by zerojay** [comment] 2016-02-21 01:19
There must be something more causing them to not work. Are you sure that the xpad driver has been blacklisted?

**Comment by TroyPi** [comment] 2016-02-21 04:20
I am having the same issue.  It does not work in the games.  How do you know if the driver was blacklisted?

**Comment by zerojay** [comment] 2016-02-21 04:31
You can check to see if the xpad module is currently loaded into the kernel with the following:

lsmod | grep xpad

**Comment by TroyPi** [comment] 2016-02-21 04:40
and its not a US keyboard so I can't even find the |

**Comment by zerojay** [comment] 2016-02-21 04:43
Maybe redirect the output of lsmod to a text file and read it?

lsmod > test.txt
nano test.txt

**Comment by trixster1979** [comment] 2016-02-21 08:34
Ok, so lsmod | grep xpad gave this:

xpad               12293  0
ff_memless       4758  1 xpad

I added the blacklist as you instructed and lsmod | grep xpad now returns no result.

However, the controller still does not function, and also jstest will now not recognise that the pad a pad is attached either.

lsusb now lists:

Bus 001 Device 005: ID 046d:c52e Logitech, Inc.
Bus 001 Device 004: ID 045e:02d1 Microsoft Corp.
Bus 001 Device 003: IDe 0424:ec00 Standard Microsystems Corp. SMSC9512/9514 Fast Ethernet Adapter
Bus 001 Device 002: ID 0424:9514 Standard Microsystems Corp.
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

Notice that Microsoft is listed as device 4 now, not device 7 as before. I do not know if this is relevant or not.

**Comment by zerojay** [comment] 2016-02-21 14:47
Not relevant but thanks for pointing it out.

Run: sudo ps aux | grep xboxdrv

**Comment by trixster1979** [comment] 2016-02-21 18:41
That gives:

pi         15508 0.0 0.2  5972  1968 tty1    S+  18:39   0:00 grep --color=auto xboxdrv

**Comment by cyberneticwired** [comment] 2016-02-21 19:47
mine displays a long string of text when i do it

**Comment by trixster1979** [comment] 2016-02-21 20:16
Does your controller work? What text is displayed?

**Comment by zerojay** [comment] 2016-02-21 21:13
trixter, you do not have xboxdrv running at all if that's the only line you get back.

**Comment by trixster1979** [comment] 2016-02-21 21:45
Right, so how do I get xboxdrv working properly?

**Comment by zerojay** [comment] 2016-02-21 22:04
RetroPie-Setup script -> 3 Configuration -> Xboxdrv -> Enable Xboxdrv.

**Comment by trixster1979** [comment] 2016-02-21 22:10
Ok, didn't realise I had to do that, sorry for being a noob.

However after enabling it (it says something about adding stuff to rc.local) and rebooting I'm still getting nothing.

**Comment by trixster1979** [comment] 2016-02-21 22:24
I can get rc.local working with sudo sh -x /etc/cr.local

Now sudo ps aux | grep xboxdrv gives me the correct stuff and jstest will see the controller again, however I still cannot toggle any buttons. The controller won't work in Emulationstation but attempting to configure a controller does seem to detect that it's attached.

Interestingly if I unplug the controller and then replug it the console says:

[ERROR] XboxdrvDaemon::launch_controller_thread(): USB device disappeared before it could be opened

**Comment by zerojay** [comment] 2016-02-21 22:38
You can try clearing out your emulationstation setup controls by deleting /home/pi/.emulationstation/es_input.cfg I believe. Then when you boot up next, it will ask you to configure controls.

**Comment by trixster1979** [comment] 2016-02-21 22:44
I think a more fundamental problem is that even though I've now seemingly got xboxdrv running correctly (and installed the fixed xboxdrv that was pushed to the retropie-setup script the other day) and the raspberry pi can 'see' the controller, neither jstest nor Emulationstation still will not recognise any button presses. So removing es_input.cfg won't make a difference until this issue is resolved.

**Comment by cyberneticwired** [comment] 2016-02-21 22:46
Mine looks similar to yours zero.

**Comment by zerojay** [comment] 2016-02-21 22:48
You can try to recompile the xboxdrv fork we got the Xbox One controller stuff from over here (https://github.com/antekone/xboxdrv) and let us know if that works for you but beyond that, I don't see anything else that I'm able to do here if it's still not working.

**Comment by trixster1979** [comment] 2016-02-21 23:03
Cyberneticwired, does your controller work?

**Comment by cyberneticwired** [comment] 2016-02-21 23:26
No, I'm invirtuteDei from the other thread.

**Comment by cyberneticwired** [comment] 2016-02-22 04:34
I also have three different Xbox one controllers I have tried and when I do the lsusb it says it is logic3? Don't know if that means anything or not

**Comment by cyberneticwired** [comment] 2016-02-22 04:37
And when I load rims on the bottom of the screen it says Xbox pad not configured but the menu won't let me configure so it detects it for sure.

**Comment by zerojay** [comment] 2016-02-22 07:39
Make sure you've configured it in EmulationStation.

**Comment by cyberneticwired** [comment] 2016-02-22 12:05
It doesn't let me when I go to configuration menu from pressing start.

**Comment by zerojay** [comment] 2016-02-22 13:48
As mentioned above, delete es_input.cfg, restart emulationstation and try again.

**Comment by joolswills** [comment] 2016-02-22 13:50
deleting es_input.cfg will remove the hook to trigger input configuration - if removing it, you will need to reinstall emulationstation from retropie-setup menu 5 to restore the default config.

**Comment by trixster1979** [comment] 2016-02-22 13:51
Ok, I'll give that a try but why doesnt jstest work correctly? Pressing any button on the controller does not toggle the relevant on/off...

**Comment by cyberneticwired** [comment] 2016-02-22 14:34
Okay, I'm going to reinstall emulation station from source to see if that might solve the configuration issue

**Comment by joolswills** [comment] 2016-02-22 14:36
There is no benefit from doing that - reinstall from binary (after removing the es_systems.cfg)

**Comment by cyberneticwired** [comment] 2016-02-22 14:43
Dumb question, but how do I remove the config file?

**Comment by joolswills** [comment] 2016-02-22 14:44
rm ~/.emulationstation/es_systems.cfg

**Comment by joolswills** [comment] 2016-02-22 14:44
sorry es_input.cfg

**Comment by cyberneticwired** [comment] 2016-02-22 14:55
Okay deleted the config file and reinstalled emulation station from binary, still no luck. Only recognizes Keyboard in welcome screen.

**Comment by trixster1979** [comment] 2016-02-22 14:58
I'm convinced the updated xboxdrv is still not picking up the controller correctly. If it did then surely jstest would work correctly..? What exactly was done to xboxdrv to try and regain compatibility with the latest controller firmware?

**Comment by cyberneticwired** [comment] 2016-02-22 15:03
My biggest thing is I know it works because I had the same firmware on my controller and I got it working two weeks ago (had to wipe sdcard so I lost it) from some forum that I found but I can't find it again..

**Comment by trixster1979** [comment] 2016-02-22 16:17
I reckon our best bet is if you can find that forum.

**Comment by cyberneticwired** [comment] 2016-02-22 18:05
I am not hoping on it, i have been searching for it since i wiped my sd card.

**Comment by trixster1979** [comment] 2016-02-22 20:14
I've deleted the es_input.cfg file too and reinstalled from binary too. No good, both my Xbox one controllers still refuse to work. Back to the drawing board.

Did someone on Reddit say xpad miight have been updated with a fix for the newest controllers? Is it worth installing that to see if it works? How would one go about doing that?

**Comment by TroyPi** [comment] 2016-02-23 00:15
You can check to see if the xpad module is currently loaded into the kernel with the following:

lsmod | grep xpad

If it returns with any line at all, likely "xpad", it means the kernel module is still loaded and that will interfere with xboxdrv working. So we can blacklist the xpad module from loading by doing the following:

sudo nano /etc/modprobe.d/raspi-blacklist.conf (Doesn't matter if it already exists or not.)

Add in the following:
 blacklist xpad

Save the file and reboot. Then try running the above lsmod | grep xpad and see if it's loaded. If not, check your controllers and see if they are working properly and recognized.

RetroPie-Setup script -> 3 Configuration -> Xboxdrv -> Enable Xboxdrv
Mine worked after all this was done, YAHOO!

**Comment by cyberneticwired** [comment] 2016-02-23 00:31
I know I have and pretty sure trixster have already tried that, but I will try again it won't hurt.

**Comment by TroyPi** [comment] 2016-02-23 02:30
what I don't like is that I lost the function of the keyboard with exception to the f4 key.  maybe I need to set it up as a controller, another problem is, I cannot change the mapping to my US k/b

**Comment by cyberneticwired** [comment] 2016-02-23 02:39
I would rather have my controller working instead of my keyboard.

**Comment by cyberneticwired** [comment] 2016-02-24 01:29
Anyone else have suggestions? :/

**Comment by Mhnl1979** [comment] 2016-02-28 08:25
I followed the steps above from TroyPi, now my xbox controller is recognised with the white light on the wire,  but it isnt recognised by the Emulation Station.  What next.? Ive updated retropie from clean install, blacklisted xpad and updated xboxdrv and enabled it.  So no result...

**Comment by zerojay** [comment] 2016-02-28 15:03
"You can try to recompile the xboxdrv fork we got the Xbox One controller stuff from over here (https://github.com/antekone/xboxdrv) and let us know if that works for you but beyond that, I don't see anything else that I'm able to do here if it's still not working."

Has no one built the version of xboxdrv from that other repository like I mentioned earlier in the thread? If that version of xboxdrv does not work for you, there's nothing I can do for you either and you'll have to wait for that person to update his xboxdrv fork to fix it. Send him this bug as well so he's at least aware there are issues. I'll see if there are any other pull requests out there that fix this for xboxdrv but I'm not currently hopeful.

**Comment by Mhnl1979** [comment] 2016-02-28 16:57
How can I do that?  What command i have to type?  Sorry being a Noor,  but im very excited to learn ☺️

**Comment by Mhnl1979** [comment] 2016-03-04 09:39
Followed the steps from the following link after  fresh install retropie 3.5,  updating script,  updating xboxdrv,  blacklisting xpad. And it worked!  Hooray! 

http://blog.petrockblock.com/forums/topic/new-xbox-one-controller-model-1697-not-supported/

**Comment by zerojay** [comment] 2016-03-05 02:17
That link is about using xpad though...?

**Comment by Mhnl1979** [comment] 2016-03-05 13:18
I think i didn't blacklisted xpad.  Id check that out. 
But the linux-headers are also installed. So maybe that did the trick.

**Comment by trixster1979** [comment] 2016-03-05 22:36
I rolled back the firmware in one of my controllers to 2014 firmware (http://mjr.mn/XboxOnePCDriversx86) but it still does not work, either with xpad or xboxdrv. Xpad does the trick of 'seeing' and it'll show up in jstest, but again button presses will not toggle and emulation station will not recognise button presses even though it sees a pad is connected.

Were it not for other people having problems I'd start to think there was something badly wrong with my setup.

Probably a stupid q, but has anyone tried burning a fresh sd card with a new RetroPie image to see if that works with the xboxdrv update?

**Comment by cyberneticwired** [comment] 2016-03-05 23:28
Man, I gave up and just invested in a wired 360 controller for $30.

**Comment by zerojay** [comment] 2016-03-05 23:34
Just making sure, but you aren't trying to use xpad and xboxdrv at the same time, right?

**Comment by trixster1979** [comment] 2016-03-06 00:07
Nope, xpad is blacklisted, the new xboxdrv is loaded. I've tried re-enabling xpad to see if it works with the rolled-back pad firmware but it still doesn't work, so I've re-blacklisted it.

**Comment by LuisDiazUgena** [comment] 2016-03-08 17:15
Hi!

I've a xbox controller that doesn't work at all. I've checked lsmod | grep xpad and there is no output.

I've blacklisted xpad and enable xboxdvr from retropiesetup.

I got kernel Linux 4.1.18-v7+ running on Rpi2. What should I do next?

**Comment by Mhnl1979** [comment] 2016-03-08 17:47
@trixster1979 I did,  but it didn't work. Even after updating the setup script. My guess is updating the linux-headers did the trick.

**Comment by trixster1979** [comment] 2016-03-09 07:39
Yeah, judging by reports that's the only way forward, but I'm assuming it's not a permanent solution as they'll be overwritten when the system is updated.

**Comment by mindbl0wn** [comment] 2016-03-10 07:03
@Mhnl1979 so I am following the link you posted but i am stuck, I cant seem to install the linux header 4.1.13-v7+,  getting errors while dpkg.
care to help?

**Comment by Mhnl1979** [comment] 2016-03-11 21:21
I thought I red somewhere that the older Linux kernel the solution was. Good you've got it to work.  Does retropie work with two controllers? 
Cause he gave an error while connecting.

**Comment by mindbl0wn** [comment] 2016-03-12 03:51
they should work with 2 controllers, in fact even more than 2. 
I have not got to try with multiple controllers as I only have one right now which is my xbox one controller.

**Comment by trixster1979** [comment] 2016-03-12 18:21
Can you post exactly what you did?

**Comment by mindbl0wn** [comment] 2016-03-12 20:35
what i did first was find an old version of retropie, luckily i found one which was 3.1 and the kernel that came with 3.1 was 4.1.7
After that i followed the steps provided by the link @Mhnl1979 posted. 

In the link it says to install linux headers 4.1.13 but since 3.1 came with 4.1.7, I had to install that.
Then once I was done with everything, I rebooted retropie and my controller turned on and it was recognized. Also I am using xpad, I did not need to blacklist it or even install xboxdrv.
Everything is working fine.

**Comment by Twitch0815** [comment] 2016-04-25 06:58
Just going to add this, 
I have two padhacked Xbox one controllers on Retropie 3.7 only one was recognized. Second one did not even power up its led, but swapping in the latest version of Recalbox .
Seems that whatever they did with 
Patched xpad driver to support Xbox One controllers in USB mode
Fixes any issues I was having.  Can we merge whatever changes they made to the xpad driver into the Retropie release?

**Comment by HerbFargus** [comment] 2016-04-25 08:21
https://github.com/recalbox/recalbox-buildroot/pull/250

Pull requests welcome

**Comment by joolswills** [comment] 2016-04-25 10:38
We don't manage our own kernel - RetroPie sits on top of existing OS. PR would need to go to raspberrypi/linux (but they may well not want to include stuff like this)

**Comment by Twitch0815** [comment] 2016-04-25 12:59
Don't know if I did it right first pull request I have made
https://github.com/raspberrypi/linux/pull/1438
But it's there.

**Comment by joolswills** [comment] 2016-04-25 22:41
this should work when the kernel 4.4 is packaged as it includes the changes. people can test earlier by using rpi-update.

**Comment by BobocheDude** [comment] 2016-07-15 11:58
Upgrading to the latest kernel doesn't work with my :02dd Xbox one controller.  Actually nothing above works so far :(

**Comment by trixster1979** [comment] 2016-07-15 14:59
Agreed, Xbox one controllers still don't work. I've just upgraded to retropie 4 beta 2 in the hope that this has been fixed but no, xpad and xboxdrv still don't recognise either of my controllers.

**Comment by joolswills** [comment] 2016-07-15 15:01
what is the output of `uname -a` ? are you using the xpad driver or xboxdrv ? (did you try with both ?)

Unfortunately I don't have this controller, so I can't really do any testing.

**Comment by joolswills** [comment] 2016-07-15 15:06
sorry. missed where you said you tried both - stil need the output of uname -a though. Also, note that retropie is not responsible for kernel support for hardware, although I did submit a patch to enable  LED support with xpad for the raspbian kernel which should be included in their next packaged release (or via rpi-update for testing)

**Comment by joolswills** [comment] 2016-07-15 15:07
I will also see if there are any missing kernel options in the Raspbian kernel for xbox one support.

**Comment by joolswills** [comment] 2016-07-15 15:15
All options are enabled that should be

I know there have been some xpad improvements since 4.4 so you might need to wait for the next kernel version. Also did you try https://github.com/paroj/xpad ?

**Comment by afreeorange** [comment] 2016-07-15 15:21
I got the controller working on the latest stable version of RetroPie (v3.8.1) and [model 1697](http://blog.petrockblock.com/forums/topic/new-xbox-one-controller-model-1697-not-supported/) of the controller. Did not upgrade the underlying system (esp. the kernel at v4.4.11) and did not need `xboxdrv` (i.e., worked fine with `xpad`) and started with a fresh install.

```bash
# Get rpi-source... easier than dkms shenanigans with headers from here
# https://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi
#
sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source && sudo chmod +x /usr/bin/rpi-source && /usr/bin/rpi-source -q --tag-update

# Clean anything from a previous install
sudo rm -rfv /usr/src/4.4.11-v7

# Run it
sudo rpi-source

# Fetch and install the latest version of xpad. Here's my controller
# https://github.com/paroj/xpad/blob/master/xpad.c#L131
#
sudo git clone https://github.com/paroj/xpad.git /usr/src/xpad-0.4
sudo dkms install -m xpad -v 0.4
sudo reboot
```

Was quite happy to see the controller light up after a vexing couple of hours :) Hope this helps.

**Comment by ksj01** [comment] 2016-07-16 04:48
Thanks, that worked great! There were two slight changes I needed to get this to work, which involved installing bc and dkms. The modified instructions are below.

```
# Get rpi-source... easier than dkms shenanigans with headers from here
# https://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi
#
sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source && sudo chmod +x /usr/bin/rpi-source && /usr/bin/rpi-source -q --tag-update

# Clean anything from a previous install
sudo rm -rfv /usr/src/4.4.11-v7

sudo install bc

# Run it
sudo rpi-source

# Fetch and install the latest version of xpad. Here's my controller
# https://github.com/paroj/xpad/blob/master/xpad.c#L131
#
sudo git clone https://github.com/paroj/xpad.git /usr/src/xpad-0.4
sudo install dkms
sudo dkms install -m xpad -v 0.4
sudo reboot
```

**Comment by trixster1979** [comment] 2016-07-16 07:58
I have tried both xpad and xboxdrv with no luck.

uname -a prints the following:
Linux RetroPie 4.4.15-v7+ #897 SMP Tue Jul 12 18:42:55 BST 2016 armv7l GNU/Linux

I tried the fix above this post and it still did not work for either of my xbox one controllers.

**Comment by jonmarimba** [comment] 2016-07-16 16:17
Anywhere you see `sudo install` you probably want `sudo apt-get install`, otherwise @ksj01's instructions worked for me. Reboot with the controller connected via USB, hold down A when it asks you to, run through the on-screen configuration wizard and my xbox one controller is working like a champ so far.

**Comment by afreeorange** [comment] 2016-07-16 16:45
@ksj01 : Thanks for fixing that!
@trixster1979: Disable `xboxdrv`, un-blacklist `xpad`, reboot, and try this or email me if you have no luck with them:

```bash
sudo apt-get install bc dkms
sudo wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O /usr/bin/rpi-source && sudo chmod +x /usr/bin/rpi-source && /usr/bin/rpi-source -q --tag-update

sudo rm -rfv /usr/src/4.4.*

sudo rpi-source

sudo git clone https://github.com/paroj/xpad.git /usr/src/xpad-0.4
sudo dkms install -m xpad -v 0.4
sudo reboot
```

**Comment by wrongwaymarv** [comment] 2016-07-23 21:59
Hi,

I am running the latest RetroPie build (v3.8.1) and have followed the guide @afreeorange posted above. When I run **sudo dkms install -m xpad -v 0.4** I get the following:

**Creating symlink /var/lib/dkms/xpad/0.4/source ->
                 /usr/src/xpad-0.4

DKMS: add completed.
Error! echo
Your kernel headers for kernel 4.4.11+ cannot be found at
/lib/modules/4.4.11+/build or /lib/modules/4.4.11+/source.**

After a reboot my XBox One controller still does not work. Any suggestions?

**Comment by ksj01** [comment] 2016-07-23 22:39
@afreeorange Thank YOU for doing all the heavy lifting!

@wrongwaymarv try typing:
`sudo apt-get install linux-headers-generic`

**Comment by wrongwaymarv** [comment] 2016-07-24 08:41
@ksj01 I ran the **sudo apt-get install linux-headers-generic** and received the following:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package linux-headers-generic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'linux-headers-generic' has no installation candidate
pi@retropie:~ $ sudo aptitude install linux-headers-generic
No candidate version found for linux-headers-generic
No candidate version found for linux-headers-generic
No packages will be installed, upgraded, or removed.
0 packages upgraded, 0 newly installed, 0 to remove and 35 not upgraded.
Need to get 0 B of archives. After unpacking 0 B will be used.
```

I do have a Raspberry Pi Model 1 B and used the 0/1 image from RetroPie.org.uk - could this model or build be the cause of my problems?

**Comment by wrongwaymarv** [comment] 2016-07-24 09:42
Please ignore my last comment! I have finally managed to get it working. I ran a **sudo apt-get upgrade** after the above error, and followed the guide again from the start. The controller is now recognised and working! Phew.

**Comment by andrellibus** [comment] 2016-07-28 21:45
I followed the guide that @afreeorange made (thanks a lot by the way) but i have a problem, the triggers are both not recognized as inputs when i try to map the buttons from the configure main menu>configure input
Am i the only one experiencing this problem?

**Comment by ksj01** [comment] 2016-07-28 21:50
Not just you. I think it has something to do with the way the triggers are
able to sense a variable amount of pressure (think acceleration in a racing
game; pull the triggers slightly and they only slightly apply). When I was
configuring the controllers, the right trigger worked great but the left
trigger was effectively useless. I'm unsure of a solution.

-- Kevin Jacobson

**Comment by Tomino2112** [comment] 2016-08-06 08:56
Hi,

I have followed @afreeorange advice, and manage to configure my xbox 360 wireless controllers but I can use them only in the emulationstation menu. No gui nor any game does pickup the controllers and controllers keep blinking. 

When I re-enable xboxdrv controllers get "selected"  - the led stops on some position, even though both stop on position 1, but I cannot even get pass configuration. On the config screen It says it detected 2 controllers, but pressing/holding anything on the controllers does nothing. 

Any ideas? thanks!

**Comment by joolswills** [comment] 2016-08-11 02:17
I have added the updated xpad driver to retropie-setup now (under packages -> drivers). I also forced the LED config to be on.

**Comment by HerbFargus** [comment] 2016-08-11 02:18
I'll give it a test when I've got some time with my wireless 360 controllers

**Comment by joolswills** [comment] 2016-08-11 02:25
Thanks. I've tested it with my wired 360 and it works fine.

**Comment by HerbFargus** [comment] 2016-08-11 05:59
I've tested with two controllers and I can confirm it works. it was flashing a bit but it was just due to low batteries, it would still show the player but would flash intermittently.

There is the same caveat as with the logitech controllers with the triggers being treated as axes, sometimes my controllers would be unresponsive in retroarch emulators until I tapped the triggers repeatedly. to solve it I followed the guide here:

https://github.com/RetroPie/RetroPie-Setup/wiki/Logitech-controllers#l2r2-top-triggers

I basically had to set the axes to positive in `/opt/retropie/configs/all/retroarch-joypads/Xbox360WirelessReceiver(XBOX).cfg`:

```
input_r2_axis = "+5"
input_l2_axis = "+2"
```

I would presume its the same for XBox One controllers, but I don't have any to test.

**Comment by bjorse** [comment] 2016-08-13 08:40
My PowerA Xbox One MIni Controller (wired) now works thanks to the upgraded script and after upgrading xpad. It didn't work at all previously with either xboxdrv or xpad. The only thing not working is the indicator on the controller, but I can totally live without that as it's really bright anyway.

**Comment by flaregon** [comment] 2016-08-20 19:39
bjorse which guide ? I got the PowerA Xbox one mini controller, 2 days ago, and it wont read in anything. 
when I do lsusb it shows id: 24cd:541a and no other infromation.

**Comment by bjorse** [comment] 2016-08-20 20:33
No particular guide. I just updated the RetroPie script through the menu (RetroPie-Setup/retropie_setup.sh), then I updated/installed xpad, deactivated xboxdrv, and then it just worked (after reboot). Make sure xpad is not blacklisted by typing `lsmod | grep xpad`. If nothing prints out, you're fine. Otherwise, you need to remove the blacklist from `/etc/modprobe.d/blacklist.conf`.

**Comment by bjorse** [comment] 2016-08-20 20:34
Updating xpad and deactivating xboxdrv is done through the RetroPie-Setup menu as well.

**Comment by siuburu** [comment] 2016-08-21 22:54
Xpad Update and removing xboxdrv worked for me(Xbox One COD: MW Edition Controller). Hoping to see how to make  the wireless adapter work with  retropie.

**Comment by Tomino2112** [comment] 2016-08-22 11:49
Still same for me. Exactly as I described it above.  I updated retropie through the setup script and then updated xpad through the script and no change to behavior

**Comment by joolswills** [comment] 2016-08-22 13:12
@Tomino2112 did you disable xboxdrv ?

**Comment by Tomino2112** [comment] 2016-08-22 13:45
@joolswills Yes. Actually I have to add that now I was able to make some stuff work. I have re-positioned the receiver and controllers dont just stop reacting anymore. 

Unfortunately still same problem, controllers just keep blinking, "player"not being selected and I can use only one controller at a time, if I use two it behaves strangely, one controller working then suddenly not working and the other picks up etc.

**Comment by joolswills** [comment] 2016-08-22 14:06
What is the output of `for js in /dev/input/js*; do echo $js; udevadm info $js; done; dkms status` ?

**Comment by Tomino2112** [comment] 2016-08-22 15:06
One controller connected:

```
/dev/input/js*
Unknown device, --name=, --path=, or absolute path in /dev/ or /sys expected.
xpad, 0.4, 4.4.13-v7+, armv7l: installed (original_module exists)
```

Two controllers connected:

```
/dev/input/js0
P: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/input/input1/js0
N: input/js0
S: input/by-id/usb-045e_0291-joystick
S: input/by-path/platform-3f980000.usb-usb-0:1.4:1.0-joystick
E: DEVLINKS=/dev/input/by-id/usb-045e_0291-joystick /dev/input/by-path/platform-3f980000.usb-usb-0:1.4:1.0-joystick
E: DEVNAME=/dev/input/js0
E: DEVPATH=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/input/input1/js0
E: ID_BUS=usb
E: ID_FOR_SEAT=input-platform-3f980000_usb-usb-0_1_4_1_0
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL=0291
E: ID_MODEL_ENC=0291
E: ID_MODEL_ID=0291
E: ID_PATH=platform-3f980000.usb-usb-0:1.4:1.0
E: ID_PATH_TAG=platform-3f980000_usb-usb-0_1_4_1_0
E: ID_REVISION=0107
E: ID_SERIAL=045e_0291
E: ID_TYPE=generic
E: ID_USB_DRIVER=xpad
E: ID_USB_INTERFACES=:ff5d81:ff5d82:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=045e
E: ID_VENDOR_ENC=045e
E: ID_VENDOR_ID=045e
E: MAJOR=13
E: MINOR=0
E: SUBSYSTEM=input
E: TAGS=:seat:uaccess:
E: USEC_INITIALIZED=69613601

/dev/input/js1
P: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.2/input/input2/js1
N: input/js1
S: input/by-id/usb-045e_0291-if02-joystick
S: input/by-path/platform-3f980000.usb-usb-0:1.4:1.2-joystick
E: DEVLINKS=/dev/input/by-id/usb-045e_0291-if02-joystick /dev/input/by-path/platform-3f980000.usb-usb-0:1.4:1.2-joystick
E: DEVNAME=/dev/input/js1
E: DEVPATH=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.2/input/input2/js1
E: ID_BUS=usb
E: ID_FOR_SEAT=input-platform-3f980000_usb-usb-0_1_4_1_2
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL=0291
E: ID_MODEL_ENC=0291
E: ID_MODEL_ID=0291
E: ID_PATH=platform-3f980000.usb-usb-0:1.4:1.2
E: ID_PATH_TAG=platform-3f980000_usb-usb-0_1_4_1_2
E: ID_REVISION=0107
E: ID_SERIAL=045e_0291
E: ID_TYPE=generic
E: ID_USB_DRIVER=xpad
E: ID_USB_INTERFACES=:ff5d81:ff5d82:
E: ID_USB_INTERFACE_NUM=02
E: ID_VENDOR=045e
E: ID_VENDOR_ENC=045e
E: ID_VENDOR_ID=045e
E: MAJOR=13
E: MINOR=1
E: SUBSYSTEM=input
E: TAGS=:seat:uaccess:
E: USEC_INITIALIZED=86634799

xpad, 0.4, 4.4.13-v7+, armv7l: installed (original_module exists)
```

**UPDATE**:
Interesting, first time I run it with one controller it showed whats above. Then The controller was idle for ~15m and switched off. I switched it on again, run the command again and it showed:

```
/dev/input/js0
P: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/input/input1/js0
N: input/js0
S: input/by-id/usb-045e_0291-joystick
S: input/by-path/platform-3f980000.usb-usb-0:1.4:1.0-joystick
E: DEVLINKS=/dev/input/by-id/usb-045e_0291-joystick /dev/input/by-path/platform-3f980000.usb-usb-0:1.4:1.0-joystick
E: DEVNAME=/dev/input/js0
E: DEVPATH=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.4/1-1.4:1.0/input/input1/js0
E: ID_BUS=usb
E: ID_FOR_SEAT=input-platform-3f980000_usb-usb-0_1_4_1_0
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL=0291
E: ID_MODEL_ENC=0291
E: ID_MODEL_ID=0291
E: ID_PATH=platform-3f980000.usb-usb-0:1.4:1.0
E: ID_PATH_TAG=platform-3f980000_usb-usb-0_1_4_1_0
E: ID_REVISION=0107
E: ID_SERIAL=045e_0291
E: ID_TYPE=generic
E: ID_USB_DRIVER=xpad
E: ID_USB_INTERFACES=:ff5d81:ff5d82:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=045e
E: ID_VENDOR_ENC=045e
E: ID_VENDOR_ID=045e
E: MAJOR=13
E: MINOR=0
E: SUBSYSTEM=input
E: TAGS=:seat:uaccess:
E: USEC_INITIALIZED=69613601

xpad, 0.4, 4.4.13-v7+, armv7l: installed (original_module exists)
```

**Comment by joolswills** [comment] 2016-08-22 15:14
What set up do you have ? What PSU are you using ? (what's the output ?).

What is the output of dmesg` ?

**Comment by Retrosash** [comment] 2016-08-25 06:58
Hi together,

yesterday i received my new xbox one controller:
https://www.amazon.de/gp/product/B01691M0QA/ref=oh_aui_detailpage_o01_s00?ie=UTF8&psc=1

With a USB Cable it worked like a charm in Retropie 4.0 out of the box.
But i can't get it to work with the delivered wireless dongle.

Read the posts before but i'm not sure if someone got the wireless finally get to work...

cheers
Sascha

**Comment by joolswills** [comment] 2016-08-25 09:54
Not supported yet - https://github.com/paroj/xpad/issues/14

**Comment by Retrosash** [comment] 2016-08-25 11:44
Oh man, thanks for the answer.
I wish you had never wrote this...

So still waiting for support.

**Comment by chus3r** [comment] 2016-10-04 22:28
I'm a little confused when trying to follow the thread above.

We're running a Pi3, new Xbox One controller and have been unable to get the Pi to recognized the attached controller. When using xboxdrv EmulationStation would recognize a second controller, but would no buttons would allow it to be configured. Using xpad, I've not been able to get anything to work. 

When I put the following in: 
`for js in /dev/input/js*; do echo $js; udevadm info $js; done; dkms status`

I get:

`P: /devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/input/input2/js0
N: input/js0
S: input/by-id/usb-PowerA_Xbox_ONE_liquid_metal_controller_00007947A0B2CF70-joystick
S: input/by-path/platform-3f980000.usb-usb-0:1.3:1.0-joystick
E: DEVLINKS=/dev/input/by-id/usb-PowerA_Xbox_ONE_liquid_metal_controller_00007947A0B2CF70-joystick /dev/input/by-path/platform-3f980000.usb-usb-0:1.3:1.0-joystick
E: DEVNAME=/dev/input/js0
E: DEVPATH=/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/input/input2/js0
E: ID_BUS=usb
E: ID_FOR_SEAT=input-platform-3f980000_usb-usb-0_1_3_1_0
E: ID_INPUT=1
E: ID_INPUT_JOYSTICK=1
E: ID_MODEL=Xbox_ONE_liquid_metal_controller
E: ID_MODEL_ENC=Xbox\x20ONE\x20liquid\x20metal\x20controller
E: ID_MODEL_ID=543a
E: ID_PATH=platform-3f980000.usb-usb-0:1.3:1.0
E: ID_PATH_TAG=platform-3f980000_usb-usb-0_1_3_1_0
E: ID_REVISION=0101
E: ID_SERIAL=PowerA_Xbox_ONE_liquid_metal_controller_00007947A0B2CF70
E: ID_SERIAL_SHORT=00007947A0B2CF70
E: ID_TYPE=generic
E: ID_USB_DRIVER=xpad
E: ID_USB_INTERFACES=:ff47d0:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=PowerA
E: ID_VENDOR_ENC=PowerA
E: ID_VENDOR_ID=24c6
E: MAJOR=13
E: MINOR=0
E: SUBSYSTEM=input
E: TAGS=:seat:uaccess:
E: USEC_INITIALIZED=24133

xpad, 0.4, 4.4.21-v7+, armv7l: installed (original_module exists)`

I just need a little help getting this thing figured out before I try putting ROMs on here.

**Comment by chus3r** [comment] 2016-10-05 19:44
Update
FWIW - There is a nice write up from PPOLYZOS - https://ppolyzos.com/2016/08/14/retropie-on-raspberry-pi-3-with-xbox-one-controller/ (this didn't work for me thought)

Most of the other videos and guides I've seen on Reddit, YouTube, etc are all referencing old builds and there have been so many changes to RetroPie that it's not proving useful. 

I think I'm going to have to find a 360 controller somewhere and see if I can get that to work.

**Comment by Retrosash** [comment] 2016-10-05 20:09
Just one question regarding the version you're running on your pi.

I'm running 4.0 and my xbox one controller (new 1697) was running very well with an usb cable after installing the xpad driver.
Wundering about the name, too. Mine was detected as Microsoft X-Box One pad (Firmware 2015) with dmesg.

I'm also running a second xbonx one controller (1537) with the xpax driver.

Mayber your usb cable is broken.

**Comment by chus3r** [comment] 2016-10-05 20:18
@Retrosash It's brand new, but it is not from Microsoft, but PowerA, that could be the culprit. I thought it was a standard controller when I bought it. Now that you bring this up I'm going to see if I can get a Microsoft controller and see what happens.

**Comment by joolswills** [comment] 2016-10-05 20:52
I'm closing this issue now - as we now include xpad by default and it is reported as working. Those with trouble - please use the RetroPie forum for support. Thanks.

**Closed by joolswills** 2016-10-05 20:52 UTC
Labels: Gamepad
