### ISSUE TITLE
Issue with "#" in ROM Filenames

### ISSUE THREAD

**Issue by garrettmiller** [RetroPie/RetroPie-Setup#832] opened 2015-05-14 20:22 UTC
Hi all,

Under 3.0b2, I was finding that roughly 50% of my GBA roms were segfaulting, and roughly 50% were working.   They all work fine under 2.6.  I’ve narrowed it down to a point where I found that the ones segfaulting were ones that contained a “#” in the filename. Output of runcommand.log is as follows:

```/opt/retropie/supplementary/runcommand/runcommand.sh: line 671: 2333 Segmentation fault /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-gpsp/gpsp_libretro.so --config /opt/retropie/configs/gba/retroarch.cfg "/home/pi/RetroPie/roms/gba/Advanced Wars # GBA.GBA" --appendconfig /tmp/retroarch.cfg```

The strange thing is, they all worked under 2.6, and don’t work under 3.0b2 – and it appears to have to do with the “#” in the rom name When I used the “rename” utility to rename these, it works. Behavior seems to be the same under lr-gpsp and gpsp.

Also posted about here:  http://blog.petrockblock.com/forums/topic/issue-with-gba-emulation-possible-filename-issue/

**Comment by garrettmiller** [comment] 2015-05-17 05:14
It may have to do with a difference of the ROM argument being passed in by "$2" instead of "$@" now?

**Comment by joolswills** [comment] 2015-08-13 02:56
It's a retroarch issue that needs debugging - Ill open a ticket at retroarch.

**Comment by joolswills** [comment] 2015-08-13 03:21
https://github.com/libretro/RetroArch/issues/2038

**Comment by joolswills** [comment] 2015-08-13 03:43
Actually it looks like it might be specific to gpsp. Not sure why they worked under 2.6 as I tried with an older libretro gpsp code and it still segfaulted, but it's reproducible from commandline, so it's not related to the way we launch stuff.

**Comment by joolswills** [comment] 2015-08-13 03:44
I have tested gpsp, and it works fine with roms with # in the filename - it's just the libretro core.

**Comment by garrettmiller** [comment] 2015-08-13 12:15
Cool - thanks for looking into it.  It was causing me some weirdness (my GBA romset had a number of #'s in filenames as it came) so that's what I was able to run down.  I wonder what's different about the libretro core vs. regular gpsp?  I had tried that as a debugging step myself but figured it might have been the way we were launching since regular gpsp didn't reproduce this error.

Thanks!

**Comment by joolswills** [comment] 2015-10-15 03:07
This is confirmed as a bug upstream, but it is being considered minor. in the meantime, people will just have to rename their romsets if they contain a #

**Comment by garrettmiller** [comment] 2015-10-15 03:15
Good to hear.  Thanks for the info!

**Comment by garrettmiller** [comment] 2016-04-13 14:49
As of 4/13/2016, this bug still exists.

**Comment by joolswills** [comment] 2016-04-13 17:09
You can follow the upstream ticket https://github.com/libretro/RetroArch/issues/2038

**Comment by joolswills** [comment] 2016-10-22 19:41
This is now resolved upstream - will close this once retropie binaries are updated with the fix.

**Comment by joolswills** [comment] 2016-10-22 20:50
RetroArch binaries have been updated.

**Closed by joolswills** 2016-10-22 20:50 UTC
Labels: upstream bug
