### ISSUE TITLE
ScummVM Mouse Issue

### ISSUE THREAD

**Issue by Ltty** [RetroPie/RetroPie-Setup#1337] opened 2016-03-05 15:09 UTC
Not sure if that's the right place to post this bug, but in the latest release of retro pie, the mouse automatically moves into the left upper corner and therefore is unable to use. This bug seems to be related to a similar issue on Windows where a certain SDL version is causing this issue.

Does anybody know how to solve it?

**Comment by joolswills** [comment] 2016-03-05 15:14
in the scummvm gui or ? Our scummvm is still built on SDL 1.2.x and nothing has changed with the binaries in the last version. I just loaded scummvm and the mouse pointer is moving fine in the gui.

**Comment by Ltty** [comment] 2016-03-05 17:20
Yes, in the ScummVM GUI as well as in the games. I can move the mouse but
it automatically moves into the upper left corner.

Is it possible that this is hardware related, I'm using a brand new Pi 3.
Also tried with a clean install and different input devices.
Am 05.03.2016 16:14 schrieb "Jools Wills" <notifications@github.com>:

**Comment by joolswills** [comment] 2016-03-05 17:31
Don't have that trouble. Maybe you have a joystick plugged in that is causing the mouse to move ?

**Comment by joolswills** [comment] 2016-03-05 17:31
(or the mouse is not working correctly with the rpi3)  - but I cannot reproduce.

**Comment by Ltty** [comment] 2016-03-06 11:55
A keyboard was the only other controlling device connected to the Pi.
Removed the keyboard, tried various wireless and wired mouses without
success. The mouse pointer automatically moves into the upper left corner.

I can use mouse and keyboard in other emulators though, Quake 3 Arena works
for example.

I found a ScummVM bug report with the same issue on Windows here:
http://forums.libsdl.org/viewtopic.php?t=6023

I think it's related to the Pi3, don't have the issue on a Pi2 with the
same hardware.
Am 05.03.2016 18:31 schrieb "Jools Wills" <notifications@github.com>:

**Comment by joolswills** [comment] 2016-03-06 12:20
I don't think that issue is related. Do you have a sufficient PSU on the rpi3 ? Have you tried another PSU ?

**Comment by joolswills** [comment] 2016-03-06 12:22
Unfortunately it is working fine here, so I am not sure what I can do further.

**Comment by HerbFargus** [comment] 2016-03-06 23:12
Just tried the latest build and no issues. some must be something on your end.

**Comment by joolswills** [comment] 2016-03-06 23:16
the upcoming version (will have binaries uploaded shortly) will use SDL2 instead of SDL1 o you can try that and see if it helps, but if not I suspect it's a problem related to hardware or firmware incompatibility or something.

**Comment by joolswills** [comment] 2016-03-08 15:05
scummvm has been updated to v1.8 - you can see if you have the same problem. It uses a different version of SDL, but since we can't reproduce the issue and no-one else has reported I am closing.

**Closed by joolswills** 2016-03-08 15:05 UTC

**Comment by Ltty** [comment] 2016-03-08 15:21
Thanks for the support. The issue does not appear anymore after the update.

*--*

*Florian Lettner | *CEO & Co-Founder

*Pocket Lifestyle IT-Solutions GmbH*



Softwarepark 26 | 4232 Hagenberg, Austria

florian@pocket-lifestyle.com

www.pocket-lifestyle.com



*Von:* Jools Wills [mailto:notifications@github.com]
*Gesendet:* Dienstag, 8. März 2016 16:06
*An:* RetroPie/RetroPie-Setup <RetroPie-Setup@noreply.github.com>
*Cc:* Florian Lettner <florian@pocket-lifestyle.com>
*Betreff:* Re: [RetroPie-Setup] ScummVM Mouse Issue (#1337)



scummvm has been updated to v1.8 - you can see if you have the same
problem. It uses a different version of SDL, but since we can't reproduce
the issue and no-one else has reported I am closing.

—
Reply to this email directly or view it on GitHub
<https://github.com/RetroPie/RetroPie-Setup/issues/1337#issuecomment-193816437>
.
