### ISSUE TITLE
vvvvvv build from source fails

### ISSUE THREAD

**Issue by burt111** [RetroPie/RetroPie-Setup#3137] opened 2020-05-12 19:39 UTC
When building from source on the pi 4 I had to edit the file 
/home/pi/RetroPie-Setup/tmp/build/vvvvvv/desktop_version/src/SoundSystem.h 
And change #include <SDL_mixer.h>
To #include <SDL2/SDL_mixer.h>

**Comment by cmitu** [comment] 2020-05-14 03:01
This looks like an issue related to your SDL2/SDL_Mixer installation (I see you opened an issue also upstream), I cannot reproduce this on a stock RetroPie installation - either on Raspbian Buster or Ubuntu/Debian.

**Comment by cmitu** [comment] 2020-05-20 03:29
Closing since it's not a RetroPie-Setup issue; can't reproduce on the latest Raspbian or on a Ubuntu install.

**Closed by cmitu** 2020-05-20 03:29 UTC
