### ISSUE TITLE
Libretro-mGba -> Broke

### ISSUE THREAD

**Issue by Omnija** [RetroPie/RetroPie-Setup#871] opened 2015-06-15 23:53 UTC
Since the last update on the source for libretro-mGba, the emulator no longer works.

RetroArch [ERROR] :: dylib_load :: dylib_load() failed: "/opt/retropie/libretrocores/lr-mgba/mgba_libretro.so: undefined symbol: binaryName".
RetroArch [ERROR] :: load_symbols :: Failed to open dynamic library: "/opt/retropie/libretrocores/lr-mgba/mgba_libretro.so"
RetroArch [ERROR] :: rarch_main_init :: Fatal error received in: "load_dynamic()"

**Comment by joolswills** [comment] 2015-06-15 23:53
I will compile and test and feedback upstream as needed. thanks.

**Comment by joolswills** [comment] 2015-06-27 20:40
I have forked and branched mgba before the pull request where it broke. I have opened a ticket upstream here - https://github.com/libretro/mgba/issues/5

**Comment by joolswills** [comment] 2015-06-27 20:42
This is temporary of course, until the problem is resolved upstream - so this ticket will remain open. thanks.

**Comment by joolswills** [comment] 2015-06-27 22:07
I have submitted a fix for the actual issue upstream. When it is included I will switch back to the libretro repository, and you can compile the latest version to test. thanks.

**Comment by joolswills** [comment] 2015-06-28 03:15
this is now fixed upstream.

**Closed by joolswills** 2015-06-28 03:15 UTC
