### ISSUE TITLE
I transform Retropie setup scripts to RPM platform, like openEuler, may support Fedora later

### ISSUE THREAD

**Issue by apple-ouyang** [RetroPie/RetroPie-Setup#3408] opened 2021-09-30 03:34 UTC
Here is my issue link in forum: 
https://retropie.org.uk/forum/topic/31422/i-transform-retropie-setup-scripts-to-rpm-platform-like-openeuler-may-support-fedora-later

I wanna create a branch called openEuler, or you can name it RPM/Fedora etc. to put srcripts that support rpm packages system

Hi guys,
I am a senior university student from China
I spent a few months getting Retropie to support the RPM package manager operating system
Retropie can now be successfully installed and run on Raspberry PI 4 with openEuler 21.03 (albeit with a few bugs)
Support for Fedora systems can be added in the future, as only a few more changes are needed
My installation method is to modify the relevant scripts such as retropie_setup. sh, change apt to dnf
The code is in the openEuler branch of my personal repository, this is the link to my Github: https://github.com/apple-ouyang/RetroPie-Setup
I really want to contribute the code to the community. I think it's better to open a branch of openEuler on RetroPie-Setup, because not all apt commands are replaced with DNF, only some necessary commands are replaced, and there is still some bugs that I can't fix
Looking forward to your reply

**Comment by cmitu** [comment] 2023-11-24 08:35
Duplicate of https://github.com/RetroPie/RetroPie-Setup/issues/2970.

**Closed by cmitu** 2023-11-24 08:35 UTC
