### ISSUE TITLE
lr-tyrquake "13284 Illegal instruction" Error - confirmed with official Pak's

### ISSUE THREAD

**Issue by Dochartaigh** [RetroPie/RetroPie-Setup#2055] opened 2017-07-26 12:51 UTC
Per this topic: [https://www.reddit.com/r/RetroPie/comments/6pjyh7/lrtyrquake_not_loading/](https://www.reddit.com/r/RetroPie/comments/6pjyh7/lrtyrquake_not_loading/)

At least 2 people have this problem with identical error logs when running official (NON-Mission) Quake pak's in id1 directory, with lr-tyrquake. Retropie version 4.2.10. Logs from Dev/shm:

`Parameters: Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-tyrquake/tyrquake_libretro.so --config /opt/retropie/configs/ports/quake/retroarch.cfg "/home/pi/RetroPie/roms/ports/quake/id1/pak0.pak" --appendconfig /dev/shm/retroarch.cfg /opt/retropie/supplementary/runcommand/runcommand.sh: line 1005: 13284 Illegal instruction /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-tyrquake/tyrquake_libretro.so --config /opt/retropie/configs/ports/quake/retroarch.cfg "/home/pi/RetroPie/roms/ports/quake/id1/pak0.pak" --appendconfig /dev/shm/retroarch.cfg`

`quake lr-tyrquake /home/pi/RetroPie/roms/ports/quake/id1/pak0.pak /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-tyrquake/tyrquake_libretro.so --config /opt/retropie/configs/ports/quake/retroarch.cfg "/home/pi/RetroPie/roms/ports/quake/id1/pak0.pak"`

Line 1005 of runcommand.sh (from the error log above) says `eval $COMMAND </dev/tty &>>"$LOG"` which means nothing to me, but maybe it'll help one of you out. The only thing different on my build is I'm on 4.2 now (these same Quake files have always worked in 4.1), and I'm using the headphone jack for composite out at 240p resolution instead of HDMI (if that has any bearing on this - I'm assuming the other person has a regular HDMI setup).

**Comment by Dagnillo** [comment] 2017-07-26 14:33
I'm the other person.... Running 4.2 with default HDMI settings.  My log showed the same error, regardless of what PAK files were present.

**Comment by psyke83** [comment] 2017-07-26 19:37
Relevant (I haven't yet had time to bisect the exact commit): https://github.com/RetroPie/RetroPie-Setup/issues/2006#issuecomment-317601846

**Comment by psyke83** [comment] 2017-07-27 00:39
I've bisected the problem to this commit: https://github.com/libretro/tyrquake/commit/2b0c9f232a9505862f10abc45558c0703a9d30b8

Latest master works is also working fine if you revert just that commit. Any ideas on why it's producing illegal instructions?

**Comment by Dochartaigh** [comment] 2017-07-27 00:43
Hi psyke83, thank you for the comments but to be completely honest I don't even know what a "commit" is in reference to RetroPie...or how to revert just that commit to make Quake work. Is this some line of code I could change in a certain file and it will make Quake work again? Or is it simply showing that a change was made, it bricked Quake, and you've narrowed it down to this certain commit?

**Comment by psyke83** [comment] 2017-07-27 00:49
Not to worry - that info is more relevant to @joolswills to help diagnose the issue. The problem is likely to need fixing upstream in the lr-tyquake repository.

**Comment by Dochartaigh** [comment] 2017-07-27 00:52
Thanks. I will await the fix!

**Comment by Dagnillo** [comment] 2017-07-27 01:30
Okay so I uninstalled then reinstalled from binary, now it crashes but the error has changed to this:

line 1005: 6044 illegal instruction

**Comment by sxales** [comment] 2017-07-31 06:59
I'll be number 3, I am made the mistake of updating today so I am getting the same error.

`Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-tyrquake/tyrquake_libretro.so --config /opt/retropie/configs/ports/quake/retroarch.cfg "/home/osmc/RetroPie/roms/ports/quake/id1/pak0.pak" --appendconfig /dev/shm/retroarch.cfg
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1005:  1693 Illegal instruction     /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-tyrquake/tyrquake_libretro.so --config /opt/retropie/configs/ports/quake/retroarch.cfg "/home/osmc/RetroPie/roms/ports/quake/id1/pak0.pak" --appendconfig /dev/shm/retroarch.cfg
`

**Comment by anunna777** [comment] 2017-08-01 18:38
Yep same here. I updated everything the other day... only Quake wouldn't launch. Re-installed lr-tyrquake but it didn't help. Uninstalled it then re-installed from source... nothing again. I've changed to different wads, looked at different launch scripts "Launching Quake and it's extras (1 year anniversary release)" and nothing works... but it did a few days ago.

-this log is with cyperghosts launch script (and folder layout for mission packs) but the same happens with official launch script on the wiki - just with a different "Illegal instruction" number. 

Parameters: 
Executing: /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-tyrquake/tyrquake_libretro.so --config /opt/retropie/configs/ports/quake/retroarch.cfg "/home/pi/RetroPie/roms/ports/quake/id1/pak0.pak" --appendconfig /dev/shm/retroarch.cfg
/opt/retropie/supplementary/runcommand/runcommand.sh: line 1005: 19832 Illegal instruction     /opt/retropie/emulators/retroarch/bin/retroarch -L /opt/retropie/libretrocores/lr-tyrquake/tyrquake_libretro.so --config /opt/retropie/configs/ports/quake/retroarch.cfg "/home/pi/RetroPie/roms/ports/quake/id1/pak0.pak" --appendconfig /dev/shm/retroarch.cfg

(I'm new to posting anything anywhere but want this sorted so thought I'd share my log).

**Comment by joolswills** [comment] 2017-08-01 19:31
Thanks. We don't need any more logs - it's a known issue and needs to be reported/fixed upstream.

**Comment by Dochartaigh** [comment] 2017-08-01 20:19
Joolswills, should we report it upstream? If so, how do we do that?

**Comment by psyke83** [comment] 2017-08-02 01:12
@joolswills Here it is, would appreciate feedback if it doesn't look right: https://github.com/libretro/tyrquake/pull/47

@Dochartaigh. No, it's already done. Just wait for the fix to be merged - thanks.

**Comment by joolswills** [comment] 2017-08-02 07:11
Thanks. Will rebuild bins later today.

**Comment by joolswills** [comment] 2017-08-05 08:33
This is fixed.

**Closed by joolswills** 2017-08-05 08:33 UTC
Labels: upstream bug
