### ISSUE TITLE
Add TRS-80 emulator sdltrs

### ISSUE THREAD

**Issue by petrockblog** [RetroPie/RetroPie-Setup#209] opened 2013-07-21 18:01 UTC
http://sourceforge.net/projects/sdltrs/files/Release-1.1.0/

**Comment by joolswills** [comment] 2015-07-27 19:08
I have now added xroar that also support the trs-80, so we can perhaps close this ?

**Comment by joolswills** [comment] 2015-08-02 22:19
Going to close as the trs-80 emulator we have works very well - includes native pi output (and is still in development)

**Comment by rclyne** [comment] 2015-09-12 16:34
xroar is an emulator for Dragon and Color Computer.  salters is an emulator for the earlier (and very different) TRS-80s

**Comment by joolswills** [comment] 2015-09-12 16:43
thanks. I'll re-open. Rather confusing with them re-using the name!

**Comment by joolswills** [comment] 2015-10-16 16:15
I have a module for this - not yet ready for adding though. Seems to miss some cleanup code on exit, and leave the framebuffer in an unusable state - but works apart from that.

**Comment by PaulGoes** [comment] 2016-02-02 20:31
I don't know what the status of this is. But wanted to let you know that I have the sdltrs emulator running on my RetroPie. 

![trs-80](https://cloud.githubusercontent.com/assets/17033322/12763350/338cb314-c9f4-11e5-80ef-6c926634a8f5.jpg)


I have created a manual that describes how I added sdltrs. Maybe this might help?

The biggest problem was to figure out how to create roms from the TRS-80 executables and basic programs. The roms that I created are virtual disks with the newdos disk operting system. On these disks I place the executable or basic file and make them autostart.

If you have any questions feel free to ask.

[sdltrs configuration.pdf](https://github.com/RetroPie/RetroPie-Setup/files/114630/sdltrs.configuration.pdf)

**Comment by joolswills** [comment] 2016-02-03 01:20
useful info - thanks.

I have a working module - rather than link against X11 I disabled the copy/paste code that needed it.

It's just waiting for me to test properly, and finalise. Did you have any trouble with SDL not being de-initialized properly on exit ? Might be due to me not providing it correct OS etc. I will check that.

**Comment by PaulGoes** [comment] 2016-02-03 08:04
I haven't encountered any troubles at exit; at exit it returns to the emulation station screen. But most of the time I switch games using the sdltrs emulator Floppy Disk Menu (staying in the emulator). If I have time this evening I will do some iterative tests starting and exiting the emulator and selecting different games from emulation station.

**Comment by PaulGoes** [comment] 2016-02-05 12:47
I have done some tests and result is that also on my system the exit is not working properly.

When I exit the emulator using <F8> it returns to the emulator station screen. From there I can select other emulators and games. But it feels a little slower. Also when I start another game on another console the last screen of the sdltrs emulator is visible during the startup of that other game (so it seems to run in the background). When I restart emulation station and select a random game, the last screen of the sdltrs emulator is still visble. Only restarting the system solves this.

For me it is not a big problem. When I use the trs-80 then it is in a session that I use the trs80 only (have to connect a keyboard to play the games). Understand that for inclusion in the RetroPie install you want this issue to be solved.

If I can help or test, let me know.

**Comment by joolswills** [comment] 2016-02-05 13:05
I think it doesn't closedown sdl correctly, I will take a look at the source when I get a change. Thanks for testing / feedback.

**Comment by HerbFargus** [comment] 2016-04-18 08:04
Just as a reference I can confirm this issue goes all the way back to 0.4 unless of course the fundamental bug lies in missing code from the window manager but unlikely

**Comment by HerbFargus** [comment] 2016-04-18 08:11
I built it on Linux mint 17.2 and it runs and exits fine

**Comment by HerbFargus** [comment] 2016-06-07 17:26
Pull request created here: https://github.com/RetroPie/RetroPie-Setup/pull/1512

**Comment by HerbFargus** [comment] 2016-06-07 17:56
@PaulGoes  it's now been added to the setup script, I wouldnt be offended if you submitted a pull request with your trs-80 theme to the [simple](https://github.com/RetroPie/es-theme-simple) and [simple dark](https://github.com/RetroPie/es-theme-simple-dark) repos

**Closed by HerbFargus** 2016-06-07 17:56 UTC
Labels: enhancement
